// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxcnoostsfjylryzkzzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4Y25vb3N0c2ZqeWxyeXprenpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MzA0NjQsImV4cCI6MjA2OTMwNjQ2NH0.0fDOtUiTuk04oK9sfCnOM_mzY5j5j5xaTfL4JdNXVyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});